Make steemd compiled at Ubuntu24.04 (#3701)
* CLeanup

* remove 16

* Update

* Continued work

* Update websocketpp to latest

* First attempt to make build passing on ubuntu20.04

* Continued

* Add missing

* Add missing

* Fix test

* Fix submodules

* Add rocksdb as a submodule

* Revert "Add rocksdb as a submodule"

This reverts commit b8536298d7d8893ff4cd22ef0fd81674c2e5a810.

* Revert "Revert "Add rocksdb as a submodule""

This reverts commit 32825165bc7636c07e2adcc7e75a837c4c54e0a9.

* Fix

* cyoencode submodule

* minor

* readme

* Fix tests

* Fix order

* Fix submodule

* 92%

* Continued work

* Revert and Fix

* Doc

* Make steemd work on ubuntu24.04

* continued

* Add missing

* Fix gmake issue

* Fix

* Debug

* Update seed nodes

---------

Co-authored-by: Zhihua Lai <zhihualai@microsoft.com>

diff --git a/deploy/Dockerfile.ubuntu24.04 b/deploy/Dockerfile.ubuntu24.04
--- a/deploy/Dockerfile.ubuntu24.04
+++ b/deploy/Dockerfile.ubuntu24.04
@@ -1,4 +1,4 @@
-FROM ubuntu:20.04 AS builder
+FROM ubuntu:24.04 AS builder
 
 # The default build params are for low memory mira version.
 # This usually are used as a witness node.
@@ -31,6 +31,7 @@ ENV DEBIAN_FRONTEND=noninteractive
 RUN apt-get update && \
     apt-get install -y \
         git \
+        libboost-all-dev \
         build-essential \
         cmake \
         libssl-dev \
@@ -46,6 +47,7 @@ RUN apt-get update && \
         libssl-dev \
         libtool \
         liblz4-tool \
+        liblzma-dev \
         ncurses-dev \
         libgflags-dev \
         zlib1g-dev \
@@ -54,24 +56,16 @@ RUN apt-get update && \
         libzstd-dev \
         wget
 
-RUN ln -s /usr/bin/make /usr/bin/gmake
-
-## default version at ubuntu20.04 is boost 1.71
-## upgrade to boost 1.78
-RUN wget https://archives.boost.io/release/1.78.0/source/boost_1_78_0.tar.gz && \
-    tar -xvzf boost_1_78_0.tar.gz && \
-    cd boost_1_78_0 && \
-    ./bootstrap.sh && \
-    ./b2 && \
-    ./b2 install
-
 WORKDIR /usr/local/src
 ADD . /usr/local/src
 
 RUN pwd && \
     git submodule update --init --recursive && \
     cd libraries/fc/vendor/websocketpp && \
-    (git apply /usr/local/src/patches/websocketpp-patch-ini-asio.patch || echo "Patch already applied or failed")
+    (git apply /usr/local/src/patches/websocketpp-patch-ini-asio.patch || echo "Patch already applied or failed") 
+
+RUN cd libraries/vendor/rocksdb && \
+    (git apply /usr/local/src/patches/rocksdb-cmake.patch || echo "Patch already applied or cannot apply")
 
 RUN mkdir -p build && \
     cd build && \
@@ -89,7 +83,7 @@ RUN mkdir -p build && \
         ..
 
 RUN cd build && \
-    make -j2
+    make -j3
     
 RUN cd build && \
     make install
@@ -109,7 +103,7 @@ RUN if [ "${DOXYGEN}" = "ON" ] ; then \
         programs/build_helpers/get_config_check.sh; \
     fi
 
-FROM ubuntu:20.04 AS final
+FROM ubuntu:24.04 AS final
 
 ARG CMAKE_BUILD_TYPE=Release
 ARG STEEM_STATIC_BUILD=ON
