continued

diff --git a/deploy/Dockerfile.ubuntu24.04 b/deploy/Dockerfile.ubuntu24.04
--- a/deploy/Dockerfile.ubuntu24.04
+++ b/deploy/Dockerfile.ubuntu24.04
@@ -31,6 +31,7 @@ ENV DEBIAN_FRONTEND=noninteractive
 RUN apt-get update && \
     apt-get install -y \
         git \
+        libboost-all-dev \
         build-essential \
         cmake \
         libssl-dev \
@@ -68,7 +69,10 @@ ADD . /usr/local/src
 RUN pwd && \
     git submodule update --init --recursive && \
     cd libraries/fc/vendor/websocketpp && \
-    (git apply /usr/local/src/patches/websocketpp-patch-ini-asio.patch || echo "Patch already applied or failed")
+    (git apply /usr/local/src/patches/websocketpp-patch-ini-asio.patch || echo "Patch already applied or failed") 
+
+RUN cd libraries/vendor/rocksdb/table && \
+    git apply /usr/local/src/patches/rocksdb.patch || echo "Patch already applied or failed"
 
 RUN mkdir -p build && \
     cd build && \
